config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  resources :friends
  resources :home
  resources :users
  resources :posts
  # orignal root pafe is this
  # root "home#index"
  root "friends#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'home/about', to: 'home#about'
  
  get 'user/id', to: 'user#show'
  # Defines the root path route ("/") 
  # root "articles#index"
      # devise_for :users, :controllers => { registrations:'users/registrations'}
end

app/models/friend.rb
class Friend < ApplicationRecord
  paginates_per 10
	belongs_to :user
	has_many :posts, dependent: :destroy
	has_one_attached :profile_image  

	resourcify
	# has_many :users, -> { distinct }, through: :roles, class_name: 'User', source: :users
	# has_many :creators, -> { where(:roles {name: :creator}) }, through: :roles, class_name: 'User', source: :users
	# def self.search(search)
	# 	where("lower(users.emal)LIKE :search OR lower(friends.first_name)LIKE :search" ,search:"%#{search.downcase}%").uniq
	# end


	validates :first_name, :last_name, length: {minimum:2, maximum:50} 
	validates :first_name, :last_name, format: {with: /\A[a-zA-Z]+\z/, message:"only latters are allowed"}
	validates :first_name, :last_name, :email, :phone, :instagram, :twitter, presence: true
	validates :email,presence: { message: "must be given please" }, uniqueness: true


	def self.ransackable_attributes(auth_object = nil)
		["first_name"]
	end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    # @friends = Friend.all.page(params[:page])
    @q = Friend.ransack(params[:q])
    @friends = @q.result.includes(:user).page(params[:page])
    # @friend = Kaminari.paginate_array(@friend).page(params[:page]).per(5)
  end

  def show  
    @friend = Friend.find(params[:id])

  end

  def new 
    @friend = current_user.friends.build
  end

  def create
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        # current_user.add_role :creater,@friend
        FriendCleanupJob.set(wait: 20.seconds).perform_later(@friend)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def acceptable_image 
   return unless profile_image.attached?
  end

  def edit
  end

  def update
    respond_to do |format|
      if @friend.update(friend_params)
         # current_user.add_role :editor,@friend
        FriendCleanupJob.set(wait: 5.seconds).perform_later(@friend)
      # CrudNotificationMailer.update_notification(@friend).deliver_now

        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    CrudNotificationMailer.delete_notification(@friend).deliver_now
    @friend = Friend.find(params[:id])
    @friend.destroy
    FriendCleanupJob.set(wait: 5.seconds).perform_later(@friend)


    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end

      # redirect_to friend_path, status: :see_other

  end

  def correct_user
    @user = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized this friend" if @friend.nil?
  end

  private
    def set_friend
      @friend = Friend.find(params[:id])
    end

    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :instagram, :user_id, :profile_image )
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_banner.html.erb
<section id="banner" >
	<div class="container">
		 <div class="col">
          <div class="header-front">
            <div class="head-title">A <span class="ht">Friend</span> is a person with whom you share a close, supportive <span class="ht">relationship.</span>
           <%= image_tag "first.png", class:"front-portion-img img-rounded",alt:"Responsive image" %>
            </div>
          </div>
        </div>
	</div>

</section>

app/views/friends/_form.html.erb
<%= bootstrap_form_with(model: friend) do |form| %>

<% if friend.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
    <ul>
      <% friend.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="container">
  
  <div class="field form-group">
    <%= form.text_field :first_name ,class:"form-control",placeholder:"first name"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name ,class:"form-control",placeholder:"last name"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :email ,class:"form-control",placeholder:"Email Id"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone ,class:"form-control",placeholder:"Phone Number"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter ,class:"form-control" ,placeholder:"Twitter"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :instagram ,class:"form-control",placeholder:"Instagram"%>
  </div>


  <div class="field form-group">
    <%= form.file_field :profile_image, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.hidden_field :user_id ,class:"form-control",value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
<i class="fa fa-car" aria-hidden="true"></i>

    <%= form.submit class:'btn btn-success'%>
  </div>
</div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <div class="jumbotron jumbo-tron mb-5 bg-body-tertiary">
    <div class="jumbo-data">
        <h1 class="display-4">
          <%= friend.first_name %>
          <%= friend.last_name %>
        </h1>
        <p class="lead">
          <%= friend.email %> |
          <%= friend.phone %> |
          <%= friend.twitter %> |
          <%= friend.instagram %>
        </p>
        <br>
        <p class="lead">
      <div>
        <%= link_to "Edit", edit_friend_path(@friend),class:"btn btn-primary" %> 
        <%= link_to "Back", friends_path,class:"btn btn-primary" %>
      </div>  </p>
    </div>
    <div class="jumbo-image ">
      <% if @friend.profile_image.attached? %>
          <%= image_tag friend.profile_image, class:"image" %>
      <% end %>
    </div>
  </div>
</div>
  

app/views/friends/edit.html.erb
<% if current_user.has_role? :admin %>

<div class="container mt-5">  
  <div class="card text-center">
    <div class="card-header">
      Editing Friend
    </div>
    <div class="card-body">
      <h5 class="card-title">Edit Friend details </h5>
      <p class="card-text"> <%= render "form", friend: @friend %></p>
      <div class="row justify-content-center">
        <%= link_to "Show", @friend, class:"btn btn-primary" %> |
        <%= link_to "Back", friends_path , class:"btn btn-dark"%> |
        <%= link_to 'delete', @friend ,
                   data: {turbo_method: :delete, turbo_confirm: :"Are You Sure?"} ,class:"btn btn-outline-danger "%>
      </div>
    </div>
  </div>
</div>
<% else %>
<h2>You're no authorized to edit this friends</h2>
<% end %>

app/views/friends/index.html.erb
<body class="index-page">
  <section class="offcanva">
  <%= link_to "Search Friend", "#offcanvasExample", data: { bs_toggle: "offcanvas" }, area: {controls: "offcanvasExample" }, role: "button", class: "btn btn-primary " %>
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasExampleLabel">Search Friends</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="container">
        <%= search_form_for @q, url: :friends do |f|%>
        <div class="form-group">
          <%= f.label :first_name_cont , class: "form-label" %>
          <%= f.search_field :first_name_cont , class: "form-control" %>
        </div>
        <div class="form-group mt-3">
          <%= f.submit 'Search Friend', class:"btn btn-primary" %>
        </div>
        <% end %>
      </div>
      <div class="offcanvas-cont">
        dvhwd
      </div>
    </div>
  </div>
</section>

  <% if user_signed_in? %>
      <div class="row">
        <div class="col">
          <div class="header-front">
            <div class="head-title">A <span class="ht">Friend</span> is a person with whom you share a close, supportive relationship.
            <%= image_tag "first.png", class:"front-portion-img img-rounded",alt:"Responsive image" %></div>
            </div>
          </div>
        </div>
      <h1>Friends List</h1>
      <div class="table-responsive ">  
        <table class="table table-bordered  table-striped table-hover">
          <thead class="thead-dark">
            <tr>
              <th>Name</th>
              <th>Email </th>
              <th>Phone number</th>
              <th>Twitter</th>
              <th>Instagram</th>
              <th colspan="1"></th>
            </tr>
          </thead>      
          <tbody>
            <% @friends.each do |friend|  %>
              <% if friend.user == current_user %>

                <tr>
                  <td><%= link_to friend.first_name + ' '+ friend.last_name, friend,class:"table-data1" %>
                  </td>
                  <td><%= friend.email %></td>
                  <td><%= friend.phone %></td>
                  <td><%= friend.twitter %></td>
                  <td><%= friend.instagram %></td>
                  <td><%= link_to 'destroy', friend_path(friend),
                   data: {turbo_method: :delete, turbo_confirm: :"Are You Sure?"} ,class:"btn btn-outline-danger btn-sm"%></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <%= paginate @friends%>
        </div>
      </div>
    </div>
  <% else %>
    <%= render 'home/front' %>
  <% end %>
</body>

app/views/friends/new.html.erb
<h1> Add New friend</h1>
<br>
<%= render "form", friend: @friend %>
<br>
<div class="m-3">
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

 					  