config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  resources :friends
  resources :home
  resources :users
  resources :posts
  # orignal root pafe is this
  # root "home#index"
  root "friends#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'home/about', to: 'home#about'
  
  get 'user/id', to: 'user#show'
  # Defines the root path route ("/") 
  # root "articles#index"
      # devise_for :users, :controllers => { registrations:'users/registrations'}
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 5

  rolify
  has_many :friends 
  has_one_attached :image
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :assign_default_role


  validate :must_have_a_role, on: :update


  def self.ransackable_attributes(auth_object = nil)
    ["email"]
  end


  def must_have_a_role
    unless roles_name
      errors.add(:roles, "must have at least one role")
    end
  end
  
  private
  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  # private 
  # def user_params
  #    params.require(:user).permit(:imgae) 
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # protected
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute], :image)
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:profile_image])
  # end

  # # The path used after sign up.
  # # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # @users = User.all
    @users = User.includes(:friends)
    @users = User.all.page(params[:page])
    

    # @q = User.ransack(params[:q])
    # @users = @q.result.includes(:user).page(params[:page])
  end

  def show
    @user = User.find_by_id(params[:id])
    @friends = User.order(:user).page params[:page]
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  #this is for direct search without gem

  # def search
  #   if params[:search].blank?
  #     redirect_to root_path
  #   else 
  #     @parameter = params[:search].downcase
  #     @matchUsers= User.where("lower(email) LIKE ?", "%#{@parameter}%")
  #     @matchFriends = Friend.all.where("lower(first_name) LIKE ? or last_name LIKE ?", "%#{@parameter}%","%#{@parameter}%")
  #   end
  # end 

  def acceptable_image 
   return unless image.attached?
  end


  def correct_user
    @user = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized this friend" if @friend.nil?
  end

  def update
    @user = User.find_by_id(params[:id])

    if @user.update(user_params)
      redirect_to users_url, notice: "User can successfuly updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  private 
  def user_params
     params.require(:user).permit({role_ids: []}) 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= bootstrap_form_with(model: @user) do |form| %>
  <%= form.collection_check_boxes :role_ids , Role.all, :id, :name%>
  <%= @user.errors[:roles] %>
  <%= form.button :submit%>
<% end %>

app/views/users/index.html.erb
<div class=""> 

  <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">Scrolling</button>

<div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Backdrop with scrolling</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <p>Try scrolling the rest of the page to see this option in action.</p>
  </div>
</div>

  <h3>Users List</h3>
  <table class="table table-bordered  table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <% if current_user.has_role? :admin %>
            <td><%= link_to  user.email, user_path(user) %></td>
            <td><%= link_to 'Edit user', edit_user_path(user)%></td>
          <% end %>
        </tr>  
          <%#= user.roles.pluck(:name) %>
      <% end %>
    </tbody>
  </table>
   <%= paginate @users %>
</div>

<div>
  
  <%#   = image_tag @user.image %>
  
</div>

app/views/users/show.html.erb
<div class="table-responsive ">  
  <h2>Friends List</h2>
  <table class="table table-bordered  table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @user.friends.each do|friend| %>
        <tr>
          <td><%=link_to friend.first_name, friend_path(friend) %></td>
        </tr>  
      <% end %>
    </tbody>
  </table>
    <%= paginate @friends, window: 2 %>
</div>