config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  resources :friends
  resources :home
  resources :users
  resources :posts
  # orignal root pafe is this
  # root "home#index"
  root "friends#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'home/about', to: 'home#about'
  
  get 'user/id', to: 'user#show'
  # Defines the root path route ("/") 
  # root "articles#index"
      # devise_for :users, :controllers => { registrations:'users/registrations'}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @users = User.without.attached_image?
  end

  def about 

  end
  
 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>

  <footer
          class="text-center text-lg-start text-white "
          style="background-color: #1c2331"
          >
    <!-- Section: Social media -->
    <section
             class="d-flex justify-content-between p-4"
             style="background-color: #6351ce"
             >
      <!-- Left -->
      <div class="me-5">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->


      <!-- Right -->
      <div>
        <a href="https://www.google.com/" class="text-white me-4" target="blank">
          <i class="bi bi-google"></i>
        </a>
        <a href="https://twitter.com/" class="text-white me-4" target="blank">
          <i class="bi bi-twitter"></i>
        </a>
        <a href="https://github.com/" class="text-white me-4" target="blank">
          <i class="bi bi-github"></i>
        </a>
        <a href="https://www.instagram.com/" class="text-white me-4" target="blank">
          <i class="bi bi-instagram"></i>
        </a>
        <a href="https://www.linkedin.com/" class="text-white me-4" target="blank">
          <i class="bi bi-linkedin"></i>
        </a>
        <a href="https://m.facebook.com/" class="text-white me-4" target="blank">
          <i class="bi bi-facebook"></i>
        </a>
      </div>

      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold">Friends</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p>
              Here you can Use website to create Own friend list and showing tahier data into other user or not. You decide to how can see that list.......
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Products</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            
            <p>
              <a href="#!" class="text-white">MDWordPress</a>
            </p>
            <p>
              <a href="#!" class="text-white">BrandFlow</a>
            </p>
            <p>
              <a href="#!" class="text-white">Bootstrap Angular</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Useful links</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p> 
              <%= link_to "Your Account ", edit_user_registration_path, class:"a-primary" %>
            </p>
           <p>
              <%= link_to 'Sign up',  new_user_registration_path, class:"a-primary" %>
            </p>
            <p>
              <a href="#!" class="text-white">Shipping Rates</a>
            </p>
            <p>
              <a href="#!" class="text-white">Help</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold">Contact</h6>
            <hr
                class="mb-4 mt-0 d-inline-block mx-auto"
                style="width: 60px; background-color: #7c4dff; height: 2px"
                />
            <p><i class="fas fa-home mr-3"></i> Indore, MP 453001, India</p>
            <p><i class="fas fa-envelope mr-3"></i> info@example.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div
         class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)"
         >
      © 2023 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/"
         >SSFriends.com</a
        >
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

<!-- End of .container -->

app/views/home/_front.html.erb
<head>
  <title>
    friends
  </title>
</head>
<body class="">

  <section class="background-image-sec">
    <div class="container">
      <div class="">
        <!-- < %= image_tag "back.jpg", class:"card-img-top" %> -->
      </div>
    </div>
  
</section>
  <section class="front-portion">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="header-front">
            <div class="head-title">A <span class="ht">Friend</span> is a person with whom you share a close, supportive <span class="ht">relationship.</span>
           <%= image_tag "first.png", class:"front-portion-img img-rounded",alt:"Responsive image" %>
            </div>
          </div>
        </div>
        
      <div class="row justify-content-center">
       <div class="row row-cols-1 row-cols-md-2 g-4">

        <div class="col">
          <div class="card " style="width: 19rem;">
            <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card"  style="width: 19rem;">
           <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card "style="width: 19rem;">
           <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional contentv This content is a little bit longer..</p>
            </div>
          </div>
        </div>
          <div class="col mt-3">
            <div class="card"style="width: 19rem;">
              <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              </div>
            </div>
          </div>
          <div class="col mt-3">
            <div class="card"style="width: 19rem;">
              <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              </div>
            </div>
          </div>

          <div class="col mt-3">
            <div class="card"style="width: 19rem;">
              <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              </div>
            </div>
          </div>
      </div>
      </div>
    </div>
    
  </section>
    <h1>Hello world</h1>
</body>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" id="nav-bar">
    <%= link_to root_path do %>
    <%= image_tag( "logois.png" , height: '50', width: '150',class: 'as') %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
    <% if user_signed_in? %> 
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", posts_path,   class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "about us ",home_about_path, class:"nav-link btn text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add friends ",new_friend_path, class:"nav-link btn text-white" %>
        </li>

        <li class="nav-item">  
          <%= link_to "Edit Profile",edit_user_registration_path, class:"nav-link  btn text-white" %>
        </li>  
      </ul>

      
      <div class="image-dropdown">
        <i class="bi bi-chevron-down"></i>
          <%= image_tag( "client.jpg", width: '40',class: ' image-signout') %>
        <div class="dropdown-data text-center " style="float:right;">
          <ul>
            <!-- <div class="im">
              <%#= image_tag( "client.jpg", width: '45',class: 'm-2 image-signout1') %>
              <#% if current_user.profile_image.attached? %>
                <#%= image_tag (current_user.profile_image style:"width:20px")%>
              <#% end %>
            </div> -->
          </ul>
          <div class="data">
            <li><%= current_user.email%></li> 
            <li><%#= link_to " show", users_path %></li>
            <li><%= link_to " show", users_path ,class: "btn btn-primary" %></li>
                  
          </div>
          <div class=" image-sign-out ml-auto ">   
            <%= link_to "Sign Out ",destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: :"Are you sure You want to log out "}  , class:" btn btn-outline-danger " %>
          </div>
        </div>
      </div>


        <% else %>
          <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home", home_index_path,   class:"nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "about us ",home_about_path, class:"nav-link btn text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class:"nav-link btn text-white" %>
            </li>  
            <li class="nav-item">
              <%= link_to "Sign In ",new_user_session_path, class:"nav-link btn  text-white" %>
            </li>  
        <% end %>
          </ul>
    </div>
  </nav>

  

app/views/home/about.html.erb
    <%= stylesheet_link_tag "custom", "sdata-turbo-track": "reload" %>


<h class="head-title">About Us.....
</h>

<div class="container parent">
  <div class="row" style="max-width: 20rem;">
    <div class="row   m-2">
      <div class="card m-2 child1">
      	<%= image_tag "back.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
      </div>
   
      <div class="card m-2 child1">
      	<%= image_tag "back.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
      </div>

      <div class="card m-2 child1">
      	<%= image_tag "back.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
      </div>

      <div class="card m-2 child1">
      	<%= image_tag "back.jpg", class:"card-img-top" %>
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
      </div>
    </div>
  </div>
</div>
 

app/views/home/index.html.erb
<head>
  <title>
    friends
  </title>
</head>
<body class="">

  <section class="background-image-sec">
    <div class="container">
      <div class="">
        <!-- < % = image_tag "back.jpg", class:"card-img-top" %> -->
      </div>
    </div>
  
</section>
  <section class="front-portion">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="header-front">
            <div class="head-title">A <span class="ht">Friend</span> is a person with whom you share a close, supportive relationship.
           <%= image_tag "first.png", class:"front-portion-img img-rounded",alt:"Responsive image" %></div>
            </div>
          </div>
        </div>

      <div class="row justify-content-center">
       <div class="row row-cols-1 row-cols-md-2 g-4">
        
        <div class="col">
          <div class="card " style="width: 19rem;">
            <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card"  style="width: 19rem;">
           <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card "style="width: 19rem;">
           <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional contentv This content is a little bit longer..</p>
            </div>
          </div>
        </div>
          <div class="col">
            <div class="card"style="width: 19rem;">
              <%= image_tag "friendslogo.jpg", class:"card-img-top" %>
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              </div>
            </div>
          </div>
      </div>
      </div>
    </div>
    
  </section>
    <h1>Hello world</h1>
</body>